export const CREATE_CART_REQUEST = "CREATE_CART_REQUEST";
export const CREATE_CART_SUCCESS = "CREATE_CART_SUCCESS";
export const CREATE_CART_RESET = "CREATE_CART_RESET";
export const CREATE_CART_ERROR = "CREATE_CART_ERROR";
export const CREATE_CART_CLEAR_ERROR = "CREATE_CART_CLEAR_ERROR";

export const GET_CARTS_REQUEST = "GET_CART_REQUEST";
export const GET_CARTS_SUCCESS = "GET_CART_SUCCESS";
export const GET_CARTS_RESET = "GET_CART_RESET";
export const GET_CARTS_ERROR = "GET_CART_ERROR";
export const GET_CARTS_CLEAR_ERROR = "GET_CART_CLEAR_ERROR";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_RESET = "GET_CART_RESET";
export const GET_CART_ERROR = "GET_CART_ERROR";
export const GET_CART_CLEAR_ERROR = "GET_CART_CLEAR_ERROR";

export const UPDATE_CART_REQUEST = "UPDATE_CART_REQUEST";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_RESET = "UPDATE_CART_RESET";
export const UPDATE_CART_ERROR = "UPDATE_CART_ERROR";
export const UPDATE_CART_CLEAR_ERROR = "UPDATE_CART_CLEAR_ERROR";

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_RESET = "DELETE_CART_RESET";
export const DELETE_CART_ERROR = "DELETE_CART_ERROR";
export const DELETE_CART_CLEAR_ERROR = "DELETE_CART_CLEAR_ERROR";